Report the reason why a fixture is being skipped by the runner
That's the difference between silently skipped tests, like

```
2021-04-22 10:47:49.268010-0400 link all[95583:19434021] LinkAll.LinkAllRegressionTest
2021-04-22 10:47:50.480002-0400 link all[95583:19434021] LinkAll.LinkAllRegressionTest : 3 ms
```

and getting some output, in both UI and in logs, so we can find/fix the reason some tests are not executed.

```
2021-04-22 10:47:49.268010-0400 link all[95583:19434021] LinkAll.LinkAllRegressionTest
2021-04-22 10:47:50.476225-0400 link all[95583:19434021] 	[SKIPREASON] An exception was thrown while loading the test.
System.Exception: Platform setting determined invalid, cannot set 'Introduced' to '592128' as it is already set for the same platform to 'None'
  at ObjCRuntime.AvailabilityAttribute.Check (System.String property, ObjCRuntime.Platform existing, ObjCRuntime.Platform updated) [0x00008] in /Users/poupou/git/main/xamarin-macios/src/ObjCRuntime/PlatformAvailability.cs:354
  at ObjCRuntime.AvailabilityAttribute.set_Introduced (ObjCRuntime.Platform value) [0x00000] in /Users/poupou/git/main/xamarin-macios/src/ObjCRuntime/PlatformAvailability.cs:371
  at ObjCRuntime.AvailabilityAttribute..ctor (ObjCRuntime.Platform introduced, ObjCRuntime.Platform deprecated, ObjCRuntime.Platform obsoleted, ObjCRuntime.Platform unavailable) [0x00006] in /Users/poupou/git/main/xamarin-macios/src/ObjCRuntime/PlatformAvailability.cs:469
  at ObjCRuntime.iOSAttribute..ctor (System.Byte major, System.Byte minor, System.Byte subminor) [0x00000] in /Users/poupou/git/main/xamarin-macios/src/ObjCRuntime/PlatformAvailability.cs:521
  at ObjCRuntime.iOSAttribute..ctor (System.Byte major, System.Byte minor) [0x00000] in /Users/poupou/git/main/xamarin-macios/src/ObjCRuntime/PlatformAvailability.cs:516
  at (wrapper managed-to-native) System.MonoCustomAttrs.GetCustomAttributesInternal(System.Reflection.ICustomAttributeProvider,System.Type,bool)
  at System.MonoCustomAttrs.GetCustomAttributesBase (System.Reflection.ICustomAttributeProvider obj, System.Type attributeType, System.Boolean inheritedOnly) [0x00013] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/corlib/System/MonoCustomAttrs.cs:128
  at System.MonoCustomAttrs.GetCustomAttributes (System.Reflection.ICustomAttributeProvider obj, System.Boolean inherit) [0x00011] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/corlib/System/MonoCustomAttrs.cs:295
  at System.Reflection.RuntimeMethodInfo.GetCustomAttributes (System.Boolean inherit) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/corlib/System.Reflection/RuntimeMethodInfo.cs:499
  at NUnit.Framework.Internal.AsyncToSyncAdapter.IsAsyncOperation (System.Reflection.MethodInfo method) [0x00001] in /Users/poupou/git/nunit/src/NUnitFramework/framework/Internal/AsyncToSyncAdapter.cs:37
  at NUnit.Framework.Internal.Builders.NUnitTestCaseBuilder.CheckTestMethodSignature (NUnit.Framework.Internal.TestMethod testMethod, NUnit.Framework.Internal.TestCaseParameters parms) [0x000f7] in /Users/poupou/git/nunit/src/NUnitFramework/framework/Internal/Builders/NUnitTestCaseBuilder.cs:182
  at NUnit.Framework.Internal.Builders.NUnitTestCaseBuilder.BuildTestMethod (NUnit.Framework.Interfaces.IMethodInfo method, NUnit.Framework.Internal.Test parentSuite, NUnit.Framework.Internal.TestCaseParameters parms) [0x00022] in /Users/poupou/git/nunit/src/NUnitFramework/framework/Internal/Builders/NUnitTestCaseBuilder.cs:62
  at NUnit.Framework.TestAttribute.BuildFrom (NUnit.Framework.Interfaces.IMethodInfo method, NUnit.Framework.Internal.Test suite) [0x00022] in /Users/poupou/git/nunit/src/NUnitFramework/framework/Attributes/TestAttribute.cs:128
  at NUnit.Framework.Internal.Builders.DefaultTestCaseBuilder.BuildSingleTestMethod (NUnit.Framework.Interfaces.IMethodInfo method, NUnit.Framework.Internal.Test suite) [0x00009] in /Users/poupou/git/nunit/src/NUnitFramework/framework/Internal/Builders/DefaultTestCaseBuilder.cs:153
  at NUnit.Framework.Internal.Builders.DefaultTestCaseBuilder.BuildFrom (NUnit.Framework.Interfaces.IMethodInfo method, NUnit.Framework.Internal.Test parentSuite) [0x000ec] in /Users/poupou/git/nunit/src/NUnitFramework/framework/Internal/Builders/DefaultTestCaseBuilder.cs:120
  at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.BuildTestCase (NUnit.Framework.Interfaces.IMethodInfo method, NUnit.Framework.Internal.TestSuite suite) [0x00001] in /Users/poupou/git/nunit/src/NUnitFramework/framework/Internal/Builders/NUnitTestFixtureBuilder.cs:228
2021-04-22 10:47:50.479098-0400 link all[95583:19434021]
  at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.AddTestCasesToFixture (NUnit.Framework.Internal.TestFixture fixture, NUnit.Framework.Interfaces.IPreFilter filter) [0x0005c] in /Users/poupou/git/nunit/src/NUnitFramework/framework/Internal/Builders/NUnitTestFixtureBuilder.cs:201
  at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.BuildFrom (NUnit.Framework.Interfaces.ITypeInfo typeInfo, NUnit.Framework.Interfaces.IPreFilter filter, NUnit.Framework.Interfaces.ITestFixtureData testFixtureData) [0x002e9] in /Users/poupou/git/nunit/src/NUnitFramework/framework/Internal/Builders/NUnitTestFixtureBuilder.cs:173
  at NUnit.Framework.TestFixtureAttribute+<BuildFrom>d__47.MoveNext () [0x00020] in /Users/poupou/git/nunit/src/NUnitFramework/framework/Attributes/TestFixtureAttribute.cs:237
  at NUnit.Framework.Internal.Builders.DefaultSuiteBuilder.BuildFrom (NUnit.Framework.Interfaces.ITypeInfo typeInfo, NUnit.Framework.Interfaces.IPreFilter filter) [0x0005e] in /Users/poupou/git/nunit/src/NUnitFramework/framework/Internal/Builders/DefaultSuiteBuilder.cs:96
2021-04-22 10:47:50.479551-0400 link all[95583:19434021]
2021-04-22 10:47:50.480002-0400 link all[95583:19434021] LinkAll.LinkAllRegressionTest : 3 ms
```